language: php
php:
  - nightly
  - 7.1
before_script:
  - composer install --prefer-source --no-interaction --dev
script:
  - phpunit --configuration phpunit.xml
  - mkdir -p build/logs
after_script:
  - php vendor/bin/coveralls -v